LEVEL_NORMAL = 0
LEVEL_IGNORE = 1
LEVEL_WARNING = 2
LEVEL_ERROR = 3

JOB_SUCCESS = 1
JOB_FAILURE = 2
JOB_ROLLING = 3

# 院线名称类型
CHAIN_NAME_SHORT = 0  # 简称
CHAIN_NAME_ZHUANZI = 1  # 专资
CHAIN_NAME_ZY = 2  # 中影
CHAIN_NAME_ZY_CODE = 3  # 中影(编码)
CHAIN_NAME_JMZX = 4  # 节目中心
# CHAIN_NAME_IMPORT_CHECK = 5  # 导入检查
CHAIN_NAME_IMPORT_CHECK = 6  # 导入检查（全名）

# 影片排次号长度
MOVIECODE_LENGTH = 12

# 账本类型
BOOK_STT_DAILY = 1  # 日报
BOOK_STT_MONTH = 2  # 月报
BOOK_STT_DAILY_ZY = 3  # 中影日报
BOOK_STT_PULLED_MERGE = 4  # 完片归档
BOOK_STT_SANDBOX = 5  # 沙盒
BOOK_STT_MONTH_ZY = 6  # 中影月报
BOOK_STT_PULLED_ZY = 7  # 中影下片
BOOK_STT_PULLED = 8  # 下片
BOOK_STT_ARTISTIC = 9  # 艺术

# 影片版本
JP = 0  # 胶片
SZ2D = 1  # 2D 数字
SZ3D = 2  # 3D 数字
IMAXJP = 3  # IMAX胶片
IMAX2D = 4  # IMAX 2D
IMAX3D = 5  # IMAX 3D
ZGJM = 6  # 中国巨幕
ZGJM3D = 7  # 中国巨幕3D

# 影片合作类型
COOPERATE_DISTRIBUTE = 'F'  # 分账
COOPERATE_BUYOUT = 'M'  # 买断
COOPERATE_DOMESTIC = 'GF'  # 国产
COOPERATE_ARTISTIC = 'YS'  # 艺术
COOPERATE_INVESTMENT = 'GT'  # 投资
COOPERATE_SURVEILLANCE = 'JC'  # 监察

STATUS_NORMAL = 0
STATUS_DELETE = 1
STATUS_CONFIRMED = 0
STATUS_UNCONFIRMED = 1
STATUS_VALID = 0
STATUS_INVALID = 1
STATUS_UPLOAD_FAILED = 2  # 任务相关的账单上传失败

STATE_INITIAL = 0
STATE_WORKING = 1
STATE_STABLED = 2
STATE_FINALLY = 4

DEVICE_OWNED = 1
DEVICE_LEASED = 2

# 待收项
MODULE_STM_SETTLEPENDING = 0
# 院线每月结算
MODULE_STM_SETTLEMONTH = 1
# 中影每月结算
MODULE_STM_SETTLE_ZY_MONTH = 2
# 中影下片结算
MODULE_STM_SETTLE_ZY_PULLED = 3

# 院线日报统计表
FILE_STT_CHAIN_DAILY = 1
# 院线月报统计表
FILE_STT_CHAIN_MONTH = 2
# 院线下片统计表
FILE_STT_CHAIN_PULLED = 3

# 中影日报统计表
FILE_STT_ZY_DAILY = 4

# 中影月报统计表
FILE_STT_ZY_MONTH = 5

# 中影下片统计表
FILE_STT_ZY_PULLED = 6

# 标准院线格式
FILE_STT_CHAIN_STANDARD = 7

# 月结文件结算格式
FILE_STM_SETTLEMONTH = 3

# 月结文件结算标准格式
FILE_STM_SETTLEMONTH_STANDARD = 8

# 月结文件结算格式
FILE_STM_SETTLEMONTHZY = 4

# 中影下片结算格式
FILE_STM_SETTLEZYPULLED = 5

# 银行账单
FILE_FNC_ACCOUNT_STATEMENT = 6

# 中影结算对象
SETTLE_ZY_UNIT = 100000

# 新建任务时，手动添加的影片分账信息
MOVIE_DISTRIBUTION_MANUALLY = 0
# 导入程序自动添加的影片分账信息
MOVIE_DISTRIBUTION_AUTOMATIC = 1

MOVIE_CONFIRM_BASE = 1
MOVIE_CONFIRM_CHAIN = 2
MOVIE_CONFIRM_PRODUCER = 3
MOVIE_CONFIRM_OPTION = 4

# 项目的报表生成模式
REPORT_MODE_ON = 0  # 在映
REPORT_MODE_OFF = 1  # 下映
REPORT_MODE_END = 2  # 已结算

# 报表类型
REPORT_TYPE_IEC = 1  # 进出口报表

# 任务类型

TASK_DAILY_UPLOAD = 1  # 院线日报上传
TASK_DAILY_LEASE_VS_LEASE = 2  # 院线日报租赁对比中影日报租赁
TASK_DAILY_MERGE_VS_ZZ = 3  # 院线日报(自购)+中影日报(租赁)VS专资
# 3,院线日报发布

TASK_MONTH_UPLOAD = 11  # 院线月报上传
TASK_MONTH_MON_VS_DAY = 12  # 院线月报全部对比院线日报全部
TASK_MONTH_LEASE_VS_LEASE = 13  # 院线月报租赁对比中影月报租赁
TASK_MONTH_MERGE_VS_ZZ = 14  # 院线月报(自购)+中影月报(租赁)VS专资

TASK_DAILY_ZY_UPLOAD = 21  # 中影日报上传
# 22, 中影日报发布
#
TASK_MONTH_ZY_UPLOAD = 23  # 中影月报上传
TASK_MONTH_ZY_MON_VS_DAY = 24  # 中影月报全部对比中影日报全部
# 25, 中影发布

TASK_PULLED_UPLOAD = 31  # 院线下片报上传
#对比任务
CHAIN_RELEASE_COMPARE_CHAIN_MONTH = 32
CHAIN_RELEASE_COMPARE_ZY_RELEASE = 33
CHAIN_ZY_COMPARE_ZHUANZI = 34
CHAIN_RELEASE_COMPARE_SETTLE = 35

TASK_PULLED_ZY_UPLOAD = 41  # 中影下片报上传
ZY_RELEASE_COMPARE_ZY_MONTH = 42
ZY_RELEASE_COMPARE_SETTLE = 43

STATIS_FINAL_COMPARE = 51
SETTLE_FINAL_COMPARE = 52

RELEASE_MOVIE_PULLED = 61
BOXOFFICE_CHAIN_MONTH_LOOK = 71

UPLOAD_FILTER_IMAX_IN_CHAIN = 1  # 允许指定影厅出现在某院线
UPLOAD_FILTER_CINEMA_IN_CHAIN = 2  # 允许IMAX影片出现在某院线

NORMAL_TASK = 0  # 普通任务
SPECIAL_TASK = 1  # 特殊任务

IMAX_CHAIN = 1
IMAX_ZHONGYING = 2
IMAX_DEFAULT = 3

SCANNED = 1
NOT_SCANNED = 0